services:
  - type: web
    name: agente-buscopsi
    runtime: python
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true
